version: "3.8"
services:
  loki:
    image: grafana/loki:2.8.3
    ports:
      - 3100:3100
    networks:
      - caddy
    user: '0'
    volumes:
      - /docker/loki:/loki
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /etc/loki/local-docker-config.yaml
        auth_enabled: false
        common:
          path_prefix: /loki
          storage:
            filesystem:
              chunks_directory: /loki/chunks
              rules_directory: /loki/rules
          replication_factor: 1
          ring:
            kvstore:
              store: inmemory
        schema_config:
          configs:
            - from: 2020-10-24
              store: boltdb-shipper
              object_store: filesystem
              schema: v11
              index:
                prefix: index_
                period: 24h
        ruler:
          alertmanager_url: http://localhost:9093
        analytics:
          reporting_enabled: false
        EOF
        /usr/bin/loki -config.file=/etc/loki/local-docker-config.yaml
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    labels:
      caddy: ${DOMAIN}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - caddy
    user: '0'
    volumes:
      - /docker/grafana:/var/lib/grafana
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    restart: unless-stopped
networks:
  caddy:
    external: true